services:
  - type: web
    name: seeker
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: TEMPLATE
        value: "0"
      - key: DEBUG_HTTP
        value: "0"
      - key: TELEGRAM
        sync: false
      - key: WEBHOOK
        sync: false
