services:
  - type: web
    name: seeker
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: TEMPLATE
        value: "2"
      - key: DEBUG_HTTP
        value: "0"
      - key: TITLE
        value: "Demo Group"
      - key: IMAGE
        value: "template/whatsapp/images/ZIvBTrQd9nP.png"
      - key: REDIRECT
        value: "https://example.com"
